[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
]

[profile.release]
debug=true

[patch.crates-io]
tower-service = { git = "https://github.com/jonhoo/tower.git", branch = "dynamic-balance" }
tower-direct-service = { git = "https://github.com/jonhoo/tower.git", branch = "dynamic-balance" }
tower-discover = { git = "https://github.com/jonhoo/tower.git", branch = "dynamic-balance"  }
tower-balance = { git = "https://github.com/jonhoo/tower.git", branch = "dynamic-balance"  }
tower-buffer = { git = "https://github.com/jonhoo/tower.git", branch = "dynamic-balance"  }
tower-util = { git = "https://github.com/jonhoo/tower.git", branch = "dynamic-balance"  }
tokio-sync = { git = "https://github.com/jonhoo/tokio.git", branch = "debug-sender-no-t-debug" }
